In [1]:
import numpy as np

# Creating 1D , 2D , 3D , 4D , 5D array

In [2]:
a1 = np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

In [3]:
a2 = np.array([[2,4],
               [8,10]])
print(a2)
print(a2.shape)

[[ 2  4]
 [ 8 10]]
(2, 2)


In [4]:
a3 = np.array([
    [[1,3],
     [2,4]],
    
    [[2,4],
     [7,9]]
])

print(a3)
print(a3.shape)

[[[1 3]
  [2 4]]

 [[2 4]
  [7 9]]]
(2, 2, 2)


In [5]:
a4 =np.array([  
    [              #batch 1
        [[3,4,5],  #block 1.1
         [6,7,8]],
    
    [[1,1,1],      # block 1.2
     [2,2,2]]
    ],
    [               # batch 2
        [[9,10,11], # block 2.1
        [12,13,14]],
        
        [[3,3,3],   # block 2.2
        [4,4,4]]
    ]
])
a4

array([[[[ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 1,  1,  1],
         [ 2,  2,  2]]],


       [[[ 9, 10, 11],
         [12, 13, 14]],

        [[ 3,  3,  3],
         [ 4,  4,  4]]]])

In [6]:
a4.shape

(2, 2, 2, 3)

In [7]:
a5 =np.array([
    [
        [              #batch 1
        [[3,4,5],  #block 1
         [6,7,8]],
    
    [[1,1,1],      # block 2
     [2,2,2]]
    ],
    [               # batch 2
        [[9,10,11], # block 1
        [12,13,14]],
        
        [[3,3,3],   # block 2
        [4,4,4]]
    ]
]
,
[
    [
    [[10,20,30],
    [40,50,60]],

    [[70,80,90],
    [100,110,120]]],

    [
    [[130,140,150],
    [160,170,180]],

     [[110,200,210],
     [220,230,240]]
    ]
]
])
a5

array([[[[[  3,   4,   5],
          [  6,   7,   8]],

         [[  1,   1,   1],
          [  2,   2,   2]]],


        [[[  9,  10,  11],
          [ 12,  13,  14]],

         [[  3,   3,   3],
          [  4,   4,   4]]]],



       [[[[ 10,  20,  30],
          [ 40,  50,  60]],

         [[ 70,  80,  90],
          [100, 110, 120]]],


        [[[130, 140, 150],
          [160, 170, 180]],

         [[110, 200, 210],
          [220, 230, 240]]]]])

In [8]:
a5.shape

(2, 2, 2, 2, 3)

# Creating Array Using Different Methods


In [9]:
arr = np.array([2,3,4],dtype=float)
arr

array([2., 3., 4.])

In [10]:
np.arange(2,13,4)      #start , stop , step

array([ 2,  6, 10])

In [11]:
np.arange(16).reshape(4,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [12]:
np.arange(16).reshape(2,2,2,2)


array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.zeros((3,3,3,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [15]:
np.zeros_like(a3)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [16]:
np.ones_like(a5)

array([[[[[1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1]]],


        [[[1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1]]]],



       [[[[1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1]]],


        [[[1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1]]]]])

In [17]:
np.random.randint(2,10,size=[2,2,2],dtype='int64')

array([[[6, 6],
        [9, 6]],

       [[8, 3],
        [6, 7]]])

In [18]:
np.random.random((3,4))

array([[0.94293141, 0.4805413 , 0.43671719, 0.24525736],
       [0.03590958, 0.91463973, 0.63899662, 0.38021616],
       [0.56677811, 0.12334269, 0.19945409, 0.13552213]])

In [19]:
np.linspace(-10,10,100,dtype=int)

array([-10, -10, -10, -10, -10,  -9,  -9,  -9,  -9,  -9,  -8,  -8,  -8,
        -8,  -8,  -7,  -7,  -7,  -7,  -7,  -6,  -6,  -6,  -6,  -6,  -5,
        -5,  -5,  -5,  -5,  -4,  -4,  -4,  -4,  -4,  -3,  -3,  -3,  -3,
        -3,  -2,  -2,  -2,  -2,  -2,  -1,  -1,  -1,  -1,  -1,   0,   0,
         0,   0,   0,   1,   1,   1,   1,   1,   2,   2,   2,   2,   2,
         3,   3,   3,   3,   3,   4,   4,   4,   4,   4,   5,   5,   5,
         5,   5,   6,   6,   6,   6,   6,   7,   7,   7,   7,   7,   8,
         8,   8,   8,   8,   9,   9,   9,   9,  10])

In [20]:
np.linspace(-10,10,10,dtype=float)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [21]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Array Attributes

In [22]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [23]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [24]:
a1.shape,a2.shape,a3.shape

((10,), (3, 4), (2, 2, 2))

In [25]:
a1.size,a2.size,a3.size

(10, 12, 8)

In [26]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int64'))

In [27]:
a1.itemsize,a2.itemsize,a3.itemsize

(4, 8, 8)

In [28]:
print(a1)
a1.astype(np.float32)

[0 1 2 3 4 5 6 7 8 9]


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [29]:
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12,24).reshape(4,3)
arr1,arr2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]))

In [30]:
arr1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [31]:
arr1 == 5

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [32]:
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
arr3 = np.arange(12,24).reshape(3,4)

In [ ]:
arr1 ** arr3

In [ ]:
arr4 = np.random.random((3,3))
arr4 = np.round(arr4*100)
arr4

# Array Functions

In [ ]:
max,min,sum,prod

In [ ]:
np.max(arr4)   # it gives from whole array

In [ ]:
np.max(arr4,axis=0)

In [ ]:
np.max(arr4,axis=1)

In [ ]:
np.min(arr4,axis=0)

In [ ]:
np.min(arr4,axis=1)

In [ ]:
np.sum(arr4)

In [ ]:
np.sum(arr4,axis=0)

In [ ]:
np.prod(arr4,axis=1)

### var, std,mean,median

In [ ]:
np.var(arr4,axis=1)

In [ ]:
np.std(arr4,axis=1)

In [ ]:
np.mean(arr4)

In [ ]:
np.median(arr4)

### sin , log , exp , round , floor , ciel , dot

In [ ]:
np.sin(arr4)

In [ ]:
np.exp(arr4)

In [ ]:
np.log(arr4)

In [ ]:
arr1 = np.arange(0,12).reshape(3,4)
arr2 = np.arange(24,36).reshape(4,3)
arr1,arr2

In [ ]:
np.dot(arr1,arr2)

In [ ]:
arr5 = np.random.random((3,5))
arr5

In [ ]:
arr5.round()

In [ ]:
np.round(arr5)

In [ ]:
np.floor(arr5)

# Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

In [ ]:
a1[0:3]

In [ ]:
a1[1::2]   # start,stop,step

In [ ]:
a2

In [ ]:
a2[1,1],a2[1,0]

In [ ]:
a3

In [ ]:
a3[0,1,1]

In [ ]:
a3[1,1,0]

In [33]:
a2[1:3,1:3]      # row start:row stop , col start:col stop

array([[ 5.,  6.],
       [ 9., 10.]])

In [34]:
a2[0::2,0::2]    # row start:row stop:step , col start:col stop:step

array([[ 0.,  2.],
       [ 8., 10.]])

In [35]:
a2[1:,0:3:2]

array([[ 4.,  6.],
       [ 8., 10.]])

In [36]:
a2[0]

array([0., 1., 2., 3.])

In [37]:
a2[:,2]

array([ 2.,  6., 10.])

In [38]:
a2[1:3,1:3]

array([[ 5.,  6.],
       [ 9., 10.]])

In [39]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [40]:
a2[::2,::3]

array([[ 0.,  3.],
       [ 8., 11.]])

In [41]:
a2[::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [42]:
a2[1,::3]

array([4., 7.])

In [43]:
a2[:2,1:]

array([[1., 2., 3.],
       [5., 6., 7.]])

In [44]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [45]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [46]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [48]:
a3[0,1,:]

array([3, 4, 5])

In [49]:
a3[1,:,1]

array([10, 13, 16])

In [51]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [54]:
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

In [52]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# Iterating

In [55]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [56]:
for i in a2:
    print(i)
    print()

[0. 1. 2. 3.]

[4. 5. 6. 7.]

[ 8.  9. 10. 11.]



In [57]:
for i in a3:
    print(i)
    print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

[[18 19 20]
 [21 22 23]
 [24 25 26]]



### np.nditer()

In [58]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [70]:
a2.reshape(4,3)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

### Transpose

In [60]:
a2.transpose()

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [61]:
a2.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

### Ravel

In [79]:
rav = a2.ravel()

In [88]:
rav[0] = 1
a2,rav

(array([[ 1.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([ 1.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]))

In [89]:
flt = a2.flatten()

In [91]:
flt[1] = 12

In [97]:
a2,flt

(array([[ 1.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([ 1., 12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]))

# Stacking

In [104]:
a2,arr2

(array([[ 1.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]))

In [107]:
np.hstack((a2,a2))

array([[ 1.,  1.,  2.,  3.,  1.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]])

In [108]:
np.vstack((a2,a2))

array([[ 1.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 1.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

# Splitting

In [109]:
a4

array([[[[ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 1,  1,  1],
         [ 2,  2,  2]]],


       [[[ 9, 10, 11],
         [12, 13, 14]],

        [[ 3,  3,  3],
         [ 4,  4,  4]]]])

In [139]:
np.hsplit(a4,2)

[array([[[[ 3,  4,  5],
          [ 6,  7,  8]]],
 
 
        [[[ 9, 10, 11],
          [12, 13, 14]]]]),
 array([[[[1, 1, 1],
          [2, 2, 2]]],
 
 
        [[[3, 3, 3],
          [4, 4, 4]]]])]

In [142]:
np.vsplit(a4,2)

[array([[[[3, 4, 5],
          [6, 7, 8]],
 
         [[1, 1, 1],
          [2, 2, 2]]]]),
 array([[[[ 9, 10, 11],
          [12, 13, 14]],
 
         [[ 3,  3,  3],
          [ 4,  4,  4]]]])]

In [124]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])


In [163]:
np.hsplit(a,2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [164]:
np.vsplit(a,2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [132]:
 a11 = np.hstack((a,a))
a11

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [136]:
a12 = np.hsplit(a11,2)
print(a12)
type(a12)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[1, 2, 3, 4],
       [5, 6, 7, 8]])]


list

In [144]:
np.hsplit(a3,3)

[array([[[ 0,  1,  2]],
 
        [[ 9, 10, 11]],
 
        [[18, 19, 20]]]),
 array([[[ 3,  4,  5]],
 
        [[12, 13, 14]],
 
        [[21, 22, 23]]]),
 array([[[ 6,  7,  8]],
 
        [[15, 16, 17]],
 
        [[24, 25, 26]]])]

In [161]:
np.vsplit(a3,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [152]:
a3 = np.arange(12).reshape(3,4)

In [158]:
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [159]:
np.hsplit(a3,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]