### np.sort
- return the sorted copy of an array

In [1]:
import numpy as np

In [2]:
a= np.random.randint(11,32,12)
a

array([17, 23, 22, 22, 26, 16, 19, 28, 20, 27, 30, 31], dtype=int32)

In [3]:
b = np.random.rand(10)
b

array([0.45064816, 0.08733738, 0.60539223, 0.83384267, 0.83745744,
       0.1591465 , 0.03943353, 0.21084777, 0.42186809, 0.49766459])

### np.random.rand :
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

### np.random.randint :
is used to get random integers from low to high values. The low value is included while the high value is excluded in the calculations.

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[93, 65, 11, 59],
       [68,  6,  3, 20],
       [18, 94, 81, 90],
       [40, 55, 25, 76],
       [97, 70, 24, 51],
       [18, 81, 99, 75]], dtype=int32)

In [5]:
np.sort(a)

array([16, 17, 19, 20, 22, 22, 23, 26, 27, 28, 30, 31], dtype=int32)

- reverse order

In [6]:
np.sort(a)[::-1]

array([31, 30, 28, 27, 26, 23, 22, 22, 20, 19, 17, 16], dtype=int32)

- axis-wise

In [7]:
b

array([[93, 65, 11, 59],
       [68,  6,  3, 20],
       [18, 94, 81, 90],
       [40, 55, 25, 76],
       [97, 70, 24, 51],
       [18, 81, 99, 75]], dtype=int32)

In [8]:
np.sort(b,axis=0)
# column-wise

array([[18,  6,  3, 20],
       [18, 55, 11, 51],
       [40, 65, 24, 59],
       [68, 70, 25, 75],
       [93, 81, 81, 76],
       [97, 94, 99, 90]], dtype=int32)

In [9]:
np.sort(b,axis=1)
# row-wise

array([[11, 59, 65, 93],
       [ 3,  6, 20, 68],
       [18, 81, 90, 94],
       [25, 40, 55, 76],
       [24, 51, 70, 97],
       [18, 75, 81, 99]], dtype=int32)

# np.append
- The numpy.append() appends values along the mentioned axis at the end of the array

In [10]:
np.append(a,120)

array([ 17,  23,  22,  22,  26,  16,  19,  28,  20,  27,  30,  31, 120])

In [11]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[93.        , 65.        , 11.        , 59.        ,  0.31182656],
       [68.        ,  6.        ,  3.        , 20.        ,  0.84517226],
       [18.        , 94.        , 81.        , 90.        ,  0.82623156],
       [40.        , 55.        , 25.        , 76.        ,  0.63295842],
       [97.        , 70.        , 24.        , 51.        ,  0.24574308],
       [18.        , 81.        , 99.        , 75.        ,  0.36736073]])

In [12]:
b.shape

(6, 4)

In [13]:
np.random.random((b.shape[1],1))

array([[0.99370469],
       [0.81827786],
       [0.25372551],
       [0.80792989]])

In [14]:
b.shape

(6, 4)

In [15]:
b

array([[93, 65, 11, 59],
       [68,  6,  3, 20],
       [18, 94, 81, 90],
       [40, 55, 25, 76],
       [97, 70, 24, 51],
       [18, 81, 99, 75]], dtype=int32)

### np.concatenate
- numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [16]:
c = np.arange(6).reshape(2,3)
d = np.arange(12,18).reshape(2,3)
c,d

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[12, 13, 14],
        [15, 16, 17]]))

In [17]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [18]:
np.concatenate((c,d),axis=0)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [19]:
np.concatenate((c,d),axis=1)


array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

### np.unique
- With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [20]:
e = np.array([12,13,14,15,16,12,18,20,20])
np.unique(e)

array([12, 13, 14, 15, 16, 18, 20])

### np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

In [21]:
a.shape

(12,)

In [22]:
np.expand_dims(a,axis=1)

array([[17],
       [23],
       [22],
       [22],
       [26],
       [16],
       [19],
       [28],
       [20],
       [27],
       [30],
       [31]], dtype=int32)

In [23]:
np.expand_dims(a,axis=0)

array([[17, 23, 22, 22, 26, 16, 19, 28, 20, 27, 30, 31]], dtype=int32)

### np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [24]:
np.where(a>20)

(array([ 1,  2,  3,  4,  7,  9, 10, 11]),)

In [25]:
a[a>20]

array([23, 22, 22, 26, 28, 27, 30, 31], dtype=int32)

In [26]:
np.where(a[a>20])    #it creates a new array and give indices of that

(array([0, 1, 2, 3, 4, 5, 6, 7]),)

In [27]:
np.where(a>20,0,a)  # replace values : (condition,if,else)

array([17,  0,  0,  0,  0, 16, 19,  0, 20,  0,  0,  0], dtype=int32)

In [28]:
np.where(a>20,0,a)

array([17,  0,  0,  0,  0, 16, 19,  0, 20,  0,  0,  0], dtype=int32)

In [29]:
np.where(a%2 == 0,0,a)

array([17, 23,  0,  0,  0,  0, 19,  0,  0, 27,  0, 31], dtype=int32)

### np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.


In [30]:
b =a.reshape(3,4)

In [31]:
np.argmax(a)

np.int64(11)

In [32]:
np.argmax(b,axis=0)

array([1, 2, 2, 2])

In [33]:
np.argmax(b,axis=1)

array([1, 3, 3])

### np.argmin

In [34]:
np.argmin(a)

np.int64(5)

In [35]:
np.argmin(b)

np.int64(5)

In [36]:
b

array([[17, 23, 22, 22],
       [26, 16, 19, 28],
       [20, 27, 30, 31]], dtype=int32)

In [37]:
np.argmin(b,axis=0)

array([0, 1, 1, 0])

In [38]:
np.argmin(b,axis=1)


array([0, 1, 0])

### np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [39]:
np.cumsum(a)

array([ 17,  40,  62,  84, 110, 126, 145, 173, 193, 220, 250, 281])

In [40]:
np.cumsum(b)

array([ 17,  40,  62,  84, 110, 126, 145, 173, 193, 220, 250, 281])

In [41]:
np.cumsum(b,axis=0)

array([[17, 23, 22, 22],
       [43, 39, 41, 50],
       [63, 66, 71, 81]])

In [42]:
np.cumsum(b,axis=1)

array([[ 17,  40,  62,  84],
       [ 26,  42,  61,  89],
       [ 20,  47,  77, 108]])

### np.cumprod

In [43]:
np.cumprod(b)

array([               17,               391,              8602,
                  189244,           4920344,          78725504,
              1495784576,       41881968128,      837639362560,
          22616262789120,   678487883673600, 21033124393881600])

In [44]:
np.cumprod(b,axis=0)

array([[   17,    23,    22,    22],
       [  442,   368,   418,   616],
       [ 8840,  9936, 12540, 19096]])

### np.percentile
numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [45]:
np.percentile(a,90)

np.float64(29.8)

In [46]:
np.percentile(a,50)

np.float64(22.5)

In [47]:
np.percentile(b,45,axis=1)

array([22.  , 21.45, 28.05])

In [48]:
np.median(a)

np.float64(22.5)

### np.histogram
Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [ ]:
np.histogram(a,[0,50])      #number b/w 0-50

(array([12]), array([ 0, 50]))

In [ ]:
np.histogram(b,[0,20,40])     #number b/w 0-20 , 20-40

(array([3, 9]), array([ 0, 20, 40]))

In [51]:
np.histogram(b,[0,20,40])


(array([3, 9]), array([ 0, 20, 40]))

### np.corrcoef
Return Pearson product-moment correlation coefficients.

- It calculates the Pearson correlation coefficient, which tells you how strongly two variables are related.

In [52]:
import numpy as np

x = [1, 2, 3, 4, 5]        # Study hours
y = [50, 60, 70, 80, 90]   # Exam scores

np.corrcoef(x, y)


array([[1., 1.],
       [1., 1.]])

In [53]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [54]:
np.isin(a,[12,13,20])

array([False, False, False, False, False, False, False, False,  True,
       False, False, False])

In [55]:
a[np.isin(a,[12,13,20])]


array([20], dtype=int32)

### np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [56]:
a

array([17, 23, 22, 22, 26, 16, 19, 28, 20, 27, 30, 31], dtype=int32)

In [57]:
b

array([[17, 23, 22, 22],
       [26, 16, 19, 28],
       [20, 27, 30, 31]], dtype=int32)

In [58]:
np.flip(a)

array([31, 30, 27, 20, 28, 19, 16, 26, 22, 22, 23, 17], dtype=int32)

In [59]:
np.flip(b)

array([[31, 30, 27, 20],
       [28, 19, 16, 26],
       [22, 22, 23, 17]], dtype=int32)

In [60]:
np.flip(b,axis=0)

array([[20, 27, 30, 31],
       [26, 16, 19, 28],
       [17, 23, 22, 22]], dtype=int32)

### np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [61]:
np.put(a,[0,1],[110,120])

In [62]:
a

array([110, 120,  22,  22,  26,  16,  19,  28,  20,  27,  30,  31],
      dtype=int32)

In [63]:
np.put(b,[0,1],[110,120])
b

array([[110, 120,  22,  22],
       [ 26,  16,  19,  28],
       [ 20,  27,  30,  31]], dtype=int32)

### np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [64]:
a

array([110, 120,  22,  22,  26,  16,  19,  28,  20,  27,  30,  31],
      dtype=int32)

In [65]:
np.delete(a,2)

array([110, 120,  22,  26,  16,  19,  28,  20,  27,  30,  31], dtype=int32)

In [66]:
b

array([[110, 120,  22,  22],
       [ 26,  16,  19,  28],
       [ 20,  27,  30,  31]], dtype=int32)

In [67]:
np.delete(b,1,axis=0)

array([[110, 120,  22,  22],
       [ 20,  27,  30,  31]], dtype=int32)

In [68]:
b

array([[110, 120,  22,  22],
       [ 26,  16,  19,  28],
       [ 20,  27,  30,  31]], dtype=int32)

In [69]:
np.delete(b,[0,2],axis=1)

array([[120,  22],
       [ 16,  28],
       [ 27,  31]], dtype=int32)

### Set functions
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [81]:
m = np.array([1,2,3,4,5,16])
n = np.array([2,4,5,9,11,13,16,17])
np.union1d(m,n)

array([ 1,  2,  3,  4,  5,  9, 11, 13, 16, 17])

In [82]:
np.intersect1d(m,n)   #returns which are common in both

array([ 2,  4,  5, 16])

In [83]:
np.setdiff1d(m,n)  #returns the elements which are not common from 1st array

array([1, 3])

In [85]:
np.setxor1d(m,n)  #returns the elements which are not common from bith arrays

array([ 1,  3,  9, 11, 13, 17])

In [88]:
np.in1d(m,16)

C:\Users\ziaah\AppData\Local\Temp\ipykernel_9480\3071740502.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,16)


array([False, False, False, False, False,  True])

In [90]:
m[np.in1d(m,16)]

C:\Users\ziaah\AppData\Local\Temp\ipykernel_9480\3163783927.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,16)]


array([16])

### np.clip
numpy.clip() function is used to Clip (limit) the values in an array
- limits the range of your numerical data, ensuring values stay within a desired boundary

In [91]:
a

array([110, 120,  22,  22,  26,  16,  19,  28,  20,  27,  30,  31],
      dtype=int32)

In [92]:
np.clip(a,a_min=25,a_max=110)

array([110, 110,  25,  25,  26,  25,  25,  28,  25,  27,  30,  31],
      dtype=int32)